name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node/npm ⚙️
        uses: ./.github/workflows/actions/setup_node_npm

      - name: Build 🏗️
        run: npm run build
