name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node/npm ⚙️
        uses: ./.github/workflows/actions/setup_node_npm

      - name: Lint ✅
        run: npm run lint
