name: npm-release

on:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches: [main]

jobs:
  npm-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      NODE_ENV: 'production'

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node/npm ⚙️
        uses: ./.github/workflows/actions/setup_node_npm

      - name: Build 🏗️
        run: npm run build

      - name: Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
