name: test

on: push

env:
  FOLDER_PATH_TEST_UNIT_REPORT: ./test-unit-report

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node/npm ⚙️
        uses: ./.github/workflows/actions/setup_node_npm

      - name: Test 🧪
        run: npm run test:report

      - name: Upload report 📈
        uses: nwtgck/actions-netlify@v4
        with:
          publish-dir: ${{ env.FOLDER_PATH_TEST_UNIT_REPORT }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_TEST_UNIT_REPORT }}

      - name: Upload coverage to Codecov 📶
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
